services:
  app:
    container_name: backend
    image: 'kitkat-backend:latest'
    build:
      context: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    env_file:
      - ./.env
    volumes:
      - ./.env:/opt/demo/.env

    ports:
      - "8080:8080"

  postgres:
    container_name: db
    image: 'postgres:16-alpine'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_URL}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-db
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_DATASOURCE_URL}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    driver: local
  redis:
    driver: local